### ISSUE TITLE
程序异常退出

### ISSUE THREAD

**Issue by xingkk** [ieasysoft/imetadata#10]
![error](https://user-images.githubusercontent.com/71958893/101457230-35671300-3970-11eb-91f0-f2fcd37dec47.jpg)

**Comment by xingkk** [comment]
interval报出的异常：
![IMG_20201209_144216](https://user-images.githubusercontent.com/71958893/101595111-d5cf3d00-3a2d-11eb-9680-fa11829d2786.jpg)

**Comment by wangxiya** [comment]
发现进程判断中可能会因过程中进程退出，导致判断过程出现异常。已修正。
