### ISSUE TITLE
ro_global_dim_space表中缺少了一些字段，会导致报错

### ISSUE THREAD

**Issue by Lixian666** [ieasysoft/imetadata#3]
![企业微信截图_16070908397760](https://user-images.githubusercontent.com/71959172/101176316-44547980-3681-11eb-9ea3-9f0a74b00dc7.png)
出现的问题**缺少相关字段**
执行以下txt文件中的sql即可解决
[ro_global_dim_space新增字段sql+视图.txt](https://github.com/ieasysoft/imetadata/files/5643365/ro_global_dim_space.sql%2B.txt)

**Comment by wangxiya** [comment]
数据库格式已经统一。
问题可以关闭！
