### ISSUE TITLE
项目地址是固定的  \\imetadata\\imetadata\\jon\\db_queue,不能更改

### ISSUE THREAD

**Issue by xingkk** [ieasysoft/imetadata#6]
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'D:\\app\\imetadata\\imetadata\\job\\db_queue'
项目的路径需是  盘符\\imetadata\\imetadata\\job\\db_queue,不然系统找不到队列路径。

**Comment by wangxiya** [comment]
修改应用程序目录可以按项目需求任意调整。
也就是目前的D:\imetadata\imetadata\job\db_queue，可以修改为D:\xxx\[app_name]\imetadata\job\db_queue

**Comment by wangxiya** [comment]
请邢凯凯再次测试

**Comment by xingkk** [comment]
> 请邢凯凯再次测试

经测试，修改第一级imetadata，项目可以正常运行
